{% set name = "pynldas2" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynldas2-{{ version }}.tar.gz
  sha256: bf406c8e626b1128d2c91c2d8156d9c4d8ecd3fbfa5a13fd01220a624620ad8d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - async-retriever <0.19,>=0.18
    - h5netcdf
    - numpy >=1.21
    - pandas >=1.0
    - pygeoutils <0.19,>=0.18
    - pyproj >=2.2
    - rioxarray >=0.11
    - xarray >=2022.03.0

test:
  imports:
    - pynldas2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynldas2
  summary: Get NLDAS2 forcing data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
