{% set name = "pynldas2" %}
{% set version = "0.19.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynldas2-{{ version }}.tar.gz
  sha256: 335dd6151857be5a1142060353695af37f17be7ffe36131fc6ed80d4ecc54ab1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - aiofiles
    - aiohttp >=3.8.3
    - nest-asyncio
    - netcdf4
    - numpy >=2
    - pandas >=1
    - pyproj >=3.0.1
    - rioxarray >=0.15
    - shapely >=2
    - xarray >=2024.7

test:
  imports:
    - pynldas2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/pynldas2
  summary: Get NLDAS2 forcing data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
